#!/usr/bin/env bash
# Publish wud through Saltbox Traefik's *file* provider.
# Writes /opt/traefik/wud.yml (watched by Traefik; no Docker labels required).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
TRAEFIK_DIR="${TRAEFIK_DIR:-/opt/traefik}"
DEST="${TRAEFIK_DIR}/wud.yml"

DOMAIN=""
if [[ -f "$ENV_FILE" ]]; then
  DOMAIN="$(grep -E '^DOMAIN=' "$ENV_FILE" | tail -1 | cut -d= -f2- | tr -d '[:space:]' | tr -d '"' | tr -d "'")"
fi
DOMAIN="${DOMAIN:-${1:-}}"
if [[ -z "$DOMAIN" ]]; then
  echo "Set DOMAIN in .env or pass it as the first argument." >&2
  exit 1
fi

if [[ ! -d "$TRAEFIK_DIR" ]]; then
  echo "Traefik config directory not found: ${TRAEFIK_DIR}" >&2
  echo "On Saltbox this is /opt/traefik (mounted at /etc/traefik in the Traefik container)." >&2
  exit 1
fi

label_of() {
  local container="$1"
  local key="$2"
  docker inspect "$container" --format "{{index .Config.Labels \"${key}\"}}" 2>/dev/null || true
}

# Copy middleware / certresolver from a catalog app so this box's error-pages,
# gzip, crowdsec, Authelia, and Cloudflare warp chain matches Traefik.
HTTPS_MW=""
HTTP_MW=""
CERT="cfdns"
for name in sonarr radarr plex tautulli overseerr jellyfin authelia; do
  mw="$(label_of "$name" "traefik.http.routers.${name}.middlewares")"
  if [[ -n "$mw" && "$mw" != "<no value>" ]]; then
    HTTPS_MW="$mw"
    HTTP_MW="$(label_of "$name" "traefik.http.routers.${name}-http.middlewares")"
    cert="$(label_of "$name" "traefik.http.routers.${name}.tls.certresolver")"
    if [[ -n "$cert" && "$cert" != "<no value>" ]]; then
      CERT="$cert"
    fi
    echo "Using Traefik chain from container '${name}'"
    break
  fi
done

if [[ -z "$HTTPS_MW" || "$HTTPS_MW" == "<no value>" ]]; then
  HTTPS_MW="globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@docker"
  echo "No catalog app found; using default HTTPS middleware."
fi
if [[ -z "$HTTP_MW" || "$HTTP_MW" == "<no value>" ]]; then
  HTTP_MW="globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker,authelia@docker"
fi

mw_yaml() {
  local IFS=','
  local part
  for part in $1; do
    part="${part#"${part%%[![:space:]]*}"}"
    part="${part%"${part##*[![:space:]]}"}"
    if [[ -n "$part" ]]; then
      printf '              - "%s"\n' "$part"
    fi
  done
}

HTTP_LIST="$(mw_yaml "$HTTP_MW")"
HTTPS_LIST="$(mw_yaml "$HTTPS_MW")"

cat > "$DEST" <<EOF
# Generated by scripts/saltbox-publish.sh — Saltbox file provider
# https://docs.saltbox.dev/reference/modules/traefik_file_template/
http:
  routers:
    wud-http:
      entryPoints:
        - web
      rule: "Host(\`wud.${DOMAIN}\`)"
      middlewares:
${HTTP_LIST}
      service: wud
      priority: 20
    wud:
      entryPoints:
        - websecure
      rule: "Host(\`wud.${DOMAIN}\`)"
      middlewares:
${HTTPS_LIST}
      service: wud
      priority: 20
      tls:
        options: securetls@file
        certResolver: ${CERT}
  services:
    wud:
      loadBalancer:
        servers:
          - url: "http://wud:3000"
EOF

echo "Wrote ${DEST}"
echo "Traefik should list wud@file within a few seconds."
echo "Verify: docker compose -f ${ROOT}/compose.yaml exec wud wget -qO- http://traefik:8080/api/http/routers | grep wud"
